-- DML script
INSERT INTO APP_USER (ID, USERNAME, PASSWORD) VALUES (APP_USER_ID_SEQ.nextval, 'admin', '$2a$12$lECaRKs2WIut8gptxDA9.OK4cHGsYmJ4gL4Rmynp.yLMfQHGWFEcO');
INSERT INTO APP_USER (ID, USERNAME, PASSWORD) VALUES (APP_USER_ID_SEQ.nextval, 'user', '$2a$12$lECaRKs2WIut8gptxDA9.OK4cHGsYmJ4gL4Rmynp.yLMfQHGWFEcO');

INSERT INTO ROLE (ID, AUTHORITY) VALUES (ROLE_ID_SEQ.nextval, 'ADMIN');
INSERT INTO ROLE (ID, AUTHORITY) VALUES (ROLE_ID_SEQ.nextval, 'USER');

INSERT INTO APP_USER_ROLE (ID, APP_USER_ID, ROLE_ID) VALUES (APP_USER_ROLE_ID_SEQ.nextval, 1 ,1);
INSERT INTO APP_USER_ROLE (ID, APP_USER_ID, ROLE_ID) VALUES (APP_USER_ROLE_ID_SEQ.nextval, 1 ,2);
INSERT INTO APP_USER_ROLE (ID, APP_USER_ID, ROLE_ID) VALUES (APP_USER_ROLE_ID_SEQ.nextval, 2 ,2);

INSERT INTO STOCK (ID, NAME, DESCRIPTION, CURRENT_PRICE, LAST_UPDATE) VALUES (STOCK_ID_SEQ.nextval, 'STOC1', 'Description 1', 1.11, SYSDATE());
INSERT INTO STOCK (ID, NAME, DESCRIPTION, CURRENT_PRICE, LAST_UPDATE) VALUES (STOCK_ID_SEQ.nextval, 'STOC2', 'Description 2', 2.22, SYSDATE());
INSERT INTO STOCK (ID, NAME, DESCRIPTION, CURRENT_PRICE, LAST_UPDATE) VALUES (STOCK_ID_SEQ.nextval, 'STOC3', 'Description 3', 2.3452, SYSDATE());
INSERT INTO STOCK (ID, NAME, DESCRIPTION, CURRENT_PRICE, LAST_UPDATE) VALUES (STOCK_ID_SEQ.nextval, 'STOC4', 'Description 4', 32.62, SYSDATE());
INSERT INTO STOCK (ID, NAME, DESCRIPTION, CURRENT_PRICE, LAST_UPDATE) VALUES (STOCK_ID_SEQ.nextval, 'STOC5', 'Description 5', 82.42, SYSDATE());

INSERT INTO STOCK_EXCHANGE (ID, NAME, DESCRIPTION, LIVE_IN_MARKET) VALUES (STOCK_EXCHANGE_ID_SEQ.nextval, 'SE1', 'Description 1', false);
INSERT INTO STOCK_EXCHANGE (ID, NAME, DESCRIPTION, LIVE_IN_MARKET) VALUES (STOCK_EXCHANGE_ID_SEQ.nextval, 'SE2', 'Description 2', false);
INSERT INTO STOCK_EXCHANGE (ID, NAME, DESCRIPTION, LIVE_IN_MARKET) VALUES (STOCK_EXCHANGE_ID_SEQ.nextval, 'SE3', 'Description 2', false);

INSERT INTO STOCK_EXCHANGE_STOCK (ID, STOCK_EXCHANGE_ID, STOCK_ID) VALUES (STOCK_EXCHANGE_STOCK_ID_SEQ.nextval, 1 ,1);
INSERT INTO STOCK_EXCHANGE_STOCK (ID, STOCK_EXCHANGE_ID, STOCK_ID) VALUES (STOCK_EXCHANGE_STOCK_ID_SEQ.nextval, 1 ,2);
INSERT INTO STOCK_EXCHANGE_STOCK (ID, STOCK_EXCHANGE_ID, STOCK_ID) VALUES (STOCK_EXCHANGE_STOCK_ID_SEQ.nextval, 1 ,3);
INSERT INTO STOCK_EXCHANGE_STOCK (ID, STOCK_EXCHANGE_ID, STOCK_ID) VALUES (STOCK_EXCHANGE_STOCK_ID_SEQ.nextval, 2 ,1);
INSERT INTO STOCK_EXCHANGE_STOCK (ID, STOCK_EXCHANGE_ID, STOCK_ID) VALUES (STOCK_EXCHANGE_STOCK_ID_SEQ.nextval, 2 ,2);
